// dirk — a terminal multiplexer that knows what its sessions are for.
//
// Copyright (C) 2026 Oddur Sigurdsson
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
// details.
//
// You should have received a copy of the GNU General Public License along with
// this program.  If not, see <https://www.gnu.org/licenses/>.

//! Completion scripts, generated from the command table.
//!
//! The surface has grown past the point where you can remember whether it is
//! `pane read` or `pane show`, and there was nothing to press Tab against.
//!
//! Generated rather than written, for the same reason the skill and the schema
//! are: three hand-maintained copies of one table is three chances for one of
//! them to describe a verb that no longer exists — and a completion that offers
//! a command which then fails is worse than no completion, because you believed
//! it.
//!
//! The ids complete too, by asking a running session. That is the half that
//! makes this worth having: `w7:p12` is not a thing anybody remembers, and it is
//! the argument almost every command wants. With no session running the shell
//! is told nothing rather than kept waiting — `dirk` answers a completion
//! request the same way it answers any other command with no session, which is
//! promptly and with a failure.

use crate::api::{COMMANDS, NOUNS};

/// Which shells have a script here.
pub const SHELLS: &[&str] = &["bash", "zsh", "fish"];

/// The verbs of one noun, in table order.
fn verbs(noun: &str) -> Vec<&'static str> {
    COMMANDS
        .iter()
        .filter_map(|c| c.name.strip_prefix(noun)?.strip_prefix('.'))
        .collect()
}

/// A one-line description of a command, for the shells that show one.
fn describes(name: &str) -> String {
    COMMANDS
        .iter()
        .find(|c| c.name == name)
        .map(|c| match c.args.is_empty() {
            true => c.answer.to_string(),
            false => format!("{} -> {}", c.args, c.answer),
        })
        .unwrap_or_default()
}

/// The completion script for one shell, or `None` if there is no such shell.
pub fn script(shell: &str) -> Option<String> {
    match shell {
        "bash" => Some(bash()),
        "zsh" => Some(zsh()),
        "fish" => Some(fish()),
        _ => None,
    }
}

/// The options that come before a command.
const OPTIONS: &[&str] = &[
    "--session",
    "--remote",
    "--no-session",
    "--skill",
    "--keys",
    "--help",
    "--version",
];

fn bash() -> String {
    let mut out = String::from(
        "# dirk completions for bash. Generated by `dirk completion bash`.\n\
         _dirk() {\n\
         \x20   local cur prev noun\n\
         \x20   cur=${COMP_WORDS[COMP_CWORD]}\n\
         \x20   prev=${COMP_WORDS[COMP_CWORD-1]}\n\
         \x20   # The noun is the first word that is one; everything before it is\n\
         \x20   # an option, and options may take a value.\n\
         \x20   local i\n\
         \x20   for ((i=1; i<COMP_CWORD; i++)); do\n\
         \x20       case \" ${COMP_WORDS[i]} \" in\n",
    );
    out.push_str(&format!(
        "            \" {} \") noun=${{COMP_WORDS[i]}}; break ;;\n",
        NOUNS.join(" \" | \" ")
    ));
    out.push_str(
        "        esac\n\
         \x20   done\n\
         \x20   case $prev in\n\
         \x20       --session) COMPREPLY=($(compgen -W \"$(dirk session list 2>/dev/null | cut -f1)\" -- \"$cur\")); return ;;\n\
         \x20       --remote) COMPREPLY=(); return ;;\n\
         \x20   esac\n\
         \x20   if [ -z \"$noun\" ]; then\n",
    );
    out.push_str(&format!(
        "        COMPREPLY=($(compgen -W \"{} {}\" -- \"$cur\")); return\n",
        NOUNS.join(" "),
        OPTIONS.join(" ")
    ));
    out.push_str("    fi\n    if [ \"$prev\" = \"$noun\" ]; then\n        case $noun in\n");
    for noun in NOUNS {
        out.push_str(&format!(
            "            {noun}) COMPREPLY=($(compgen -W \"{}\" -- \"$cur\")); return ;;\n",
            verbs(noun).join(" ")
        ));
    }
    out.push_str(
        "        esac\n\
         \x20   fi\n\
         \x20   # Ids, from the session itself. Nobody remembers `w7:p12`, and it is\n\
         \x20   # the argument almost every command wants.\n\
         \x20   case $noun in\n\
         \x20       pane) COMPREPLY=($(compgen -W \"--current $(dirk pane list 2>/dev/null | sed -n 's/.*\"id\": \"\\(.*\\)\",*/\\1/p')\" -- \"$cur\")) ;;\n\
         \x20       workspace|agent) COMPREPLY=($(compgen -W \"--current $(dirk workspace list 2>/dev/null | sed -n 's/.*\"id\": \"\\(.*\\)\",*/\\1/p')\" -- \"$cur\")) ;;\n\
         \x20       layout) COMPREPLY=($(compgen -W \"$(dirk layout list 2>/dev/null | sed -n 's/.*\"name\": \"\\(.*\\)\",*/\\1/p')\" -- \"$cur\")) ;;\n\
         \x20   esac\n\
         }\n\
         complete -F _dirk dirk\n",
    );
    out
}

fn zsh() -> String {
    let mut out = String::from(
        "#compdef dirk\n\
         # dirk completions for zsh. Generated by `dirk completion zsh`.\n\
         _dirk_ids() {\n\
         \x20   dirk \"$1\" list 2>/dev/null | sed -n 's/.*\"id\": \"\\(.*\\)\",*/\\1/p'\n\
         }\n\
         _dirk() {\n\
         \x20   local -a nouns verbs ids\n",
    );
    out.push_str(&format!("    nouns=({})\n", NOUNS.join(" ")));
    out.push_str(
        "    local noun=\"\" i\n\
         \x20   for ((i = 2; i < CURRENT; i++)); do\n\
         \x20       if (( ${nouns[(I)${words[i]}]} )); then noun=${words[i]}; break; fi\n\
         \x20   done\n\
         \x20   if [[ -z $noun ]]; then\n",
    );
    out.push_str(&format!(
        "        _describe 'noun' nouns && return\n        compadd {} && return\n",
        OPTIONS.join(" ")
    ));
    out.push_str(
        "    fi\n    if [[ ${words[CURRENT-1]} == $noun ]]; then\n        case $noun in\n",
    );
    for noun in NOUNS {
        let described: Vec<String> = verbs(noun)
            .iter()
            .map(|v| {
                format!(
                    "'{v}:{}'",
                    describes(&format!("{noun}.{v}")).replace('\'', "")
                )
            })
            .collect();
        out.push_str(&format!(
            "            {noun}) verbs=({}); _describe 'verb' verbs; return ;;\n",
            described.join(" ")
        ));
    }
    out.push_str(
        "        esac\n\
         \x20   fi\n\
         \x20   case $noun in\n\
         \x20       pane) ids=(--current ${(f)\"$(_dirk_ids pane)\"}); compadd -a ids ;;\n\
         \x20       workspace|agent) ids=(--current ${(f)\"$(_dirk_ids workspace)\"}); compadd -a ids ;;\n\
         \x20   esac\n\
         }\n\
         _dirk \"$@\"\n",
    );
    out
}

fn fish() -> String {
    let mut out = String::from(
        "# dirk completions for fish. Generated by `dirk completion fish`.\n\
         function __dirk_noun\n\
         \x20   set -l words (commandline -opc)\n\
         \x20   for w in $words[2..-1]\n",
    );
    out.push_str(&format!(
        "        if contains -- $w {}\n            echo $w\n            return 0\n        end\n",
        NOUNS.join(" ")
    ));
    out.push_str(
        "    end\n\
         \x20   return 1\n\
         end\n\
         function __dirk_ids\n\
         \x20   dirk $argv[1] list 2>/dev/null | string match -r '\"id\": \"(.*)\"' -g\n\
         end\n\
         complete -c dirk -f\n",
    );
    for noun in NOUNS {
        out.push_str(&format!(
            "complete -c dirk -n 'not __dirk_noun' -a {noun} -d '{}'\n",
            verbs(noun).join(", ")
        ));
        for verb in verbs(noun) {
            let d = describes(&format!("{noun}.{verb}")).replace('\'', "");
            out.push_str(&format!(
                "complete -c dirk -n '__dirk_noun | string match -q {noun}; and not __fish_seen_subcommand_from {verb}' -a {verb} -d '{d}'\n"
            ));
        }
    }
    out.push_str(
        "complete -c dirk -n '__dirk_noun | string match -qr \"^(pane)$\"' -a '(__dirk_ids pane)'\n\
         complete -c dirk -n '__dirk_noun | string match -qr \"^(workspace|agent)$\"' -a '(__dirk_ids workspace)'\n",
    );
    for opt in OPTIONS {
        out.push_str(&format!(
            "complete -c dirk -n 'not __dirk_noun' -a '{opt}'\n"
        ));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_shell_gets_every_noun_and_every_verb() {
        // The failure this exists to prevent: a table grows a verb and one of
        // the three scripts does not, so Tab quietly stops offering it.
        for shell in SHELLS {
            let text = script(shell).expect("a script for a listed shell");
            for noun in NOUNS {
                assert!(text.contains(noun), "{shell} does not know the noun {noun}");
            }
            for cmd in COMMANDS {
                let (_, verb) = cmd.name.split_once('.').unwrap();
                assert!(
                    text.contains(verb),
                    "{shell} does not know the verb {}",
                    cmd.name
                );
            }
        }
    }

    #[test]
    fn a_shell_with_no_script_is_said_so_rather_than_guessed_at() {
        assert!(script("nushell").is_none());
        assert!(script("").is_none());
    }
}
